# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  host: localhost
  encoding: utf8
  template: template0
  username: marion

development:
  <<: *default
  database: vm_ror_dev

test:
  <<: *default
  database: vm_ror_test
